### ISSUE TITLE
Building for iOS - no project file generated

### ISSUE THREAD

**Issue by songproducer** [armory3d/armory_docs#3]
```
korefile found.
Creating iOS project files.
{ Error: ENOENT: no such file or directory, stat '/Users/leotreasure/Downloads/fluidsynth-1.1.6/build/src/FluidSynth.framework/FluidSynth'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:191:20)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:177:18)
    at /Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/main.js:212:21
    at next (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/leotreasure/Downloads/fluidsynth-1.1.6/build/src/FluidSynth.framework/FluidSynth' }
{ Error: ENOENT: no such file or directory, stat '/Users/leotreasure/Downloads/fluidsynth-1.1.6/build/src/FluidSynth.framework/FluidSynth'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:191:20)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:223:18)
    at Project.searchFiles (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/Project.js:177:18)
    at /Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Kha/Kore/Tools/koremake/out/main.js:212:21
    at next (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/leotreasure/Downloads/fluidsynth-1.1.6/build/src/FluidSynth.framework/FluidSynth' }
Done.
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/bash
  Reason: image not found
```

also in Kode studio:

```
Error processing "launch": TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at launch.then (/Applications/Armory/blender.app/armsdk/Kode Studio.app/Contents/Resources/app/extensions/chrome-debug/out/chromeDebugAdapter.js:26:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by luboslenco** [comment]
Hi,

Since it does not even work in Kode Studio - can you get any Armory project to work in Kode Studio or Blender itself?

**Comment by songproducer** [comment]
I can get scene1.blend to work in Blender viewport, but not in Kode Studio html5. (Using forward_low):

```
"Cannot read property 'COLOR_ATTACHMENT0_WEBGL' of null"

"TypeError: Cannot read property 'COLOR_ATTACHMENT0_WEBGL' of null
    at Object.begin (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:31040:76)
    at Object.setTarget (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:8718:29)
    at Array.f (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:32154:242)
    at Object.renderFrame (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:8671:25)
    at Object.renderFrame (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:10957:19)
    at Object.renderFrame (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:3583:15)
    at iron_App.render (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:2345:21)
    at Function.kha_System.render (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:15231:3)
    at animate (file:///Users/leotreasure/Downloads/build/debug-html5/kha.js:15616:15)"
```

Krom crashes with this:

`Unhandled error in debug adapter - Unhandled promise rejection: {"id":2010,"format":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:18245","_timeout":"10000"}}`

**Comment by luboslenco** [comment]
Any luck with this using latest builds?
